-- Seed: development data for local Supabase instance
-- Applied automatically by `supabase db reset`
-- Do NOT run against staging or production.
--
-- Intentionally empty. The legacy deterministic TSBVI seed was removed.
